name: Build

on: [push]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile (GCC)
      run: make
    - name: Upload
      uses: actions/upload-artifact@v4
      with: 
        name: xenon-bltool-linux-ubuntu
        path: |
          xenon-bltool
  macOS:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Compile (Clang)
      run: make
    - name: Upload
      uses: actions/upload-artifact@v4
      with: 
        name: xenon-bltool-macos
        path: |
          xenon-bltool
  Windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: mingw64
        install: make mingw-w64-x86_64-gcc
    - name: Compile (GCC)
      run: make CC=gcc
    - name: Upload
      uses: actions/upload-artifact@v4
      with: 
        name: xenon-bltool-windows-mingw64
        path: |
          xenon-bltool.exe
